# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f92f3375ca216be1912d1edc351443400f8f55187b7204dc420e130cb04be85ef919741e5dabf56ba7f354a8ebee21b18297cefd507f357c931a80fff4574d39

test:
  secret_key_base: f23e9759465d0ef63d05396316c68bbd485f0733e142d79b297517d6250d2babbd4763bcd37becb99320b501decf28ebb65ff484e67090acaeb48e1ae055bda2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
